name: Publish

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: n8maninger/action-golang-test@v2
        with:
          working-directory: ./a